"""harden_tenant_isolation_constraints

Revision ID: 113a591f8823
Revises: 9e80df0a44fa
Create Date: 2026-05-23 21:18:00.980539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '113a591f8823'
down_revision: Union[str, Sequence[str], None] = '9e80df0a44fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('automation_configs', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('automation_history', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('campaigns', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('customer_profiles', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('customers', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('loyalty_rewards', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('messages', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('restaurants', 'owner_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('restaurants', 'restaurant_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('reward_redemptions', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('settings', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('uix_restaurant_key', 'settings', ['restaurant_id', 'key'])
    op.alter_column('visits', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visits', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('uix_restaurant_key', 'settings', type_='unique')
    op.alter_column('settings', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reward_redemptions', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('restaurants', 'restaurant_details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('restaurants', 'owner_details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('messages', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('loyalty_rewards', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('customers', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('customer_profiles', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('campaigns', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('automation_history', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('automation_configs', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
