"""fix_tenant_isolation_constraints

Revision ID: 9e80df0a44fa
Revises: c893ab3fbe50
Create Date: 2026-05-23 14:24:16.619952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e80df0a44fa'
down_revision: Union[str, Sequence[str], None] = 'c893ab3fbe50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('automation_summaries', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('business_summaries', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('campaign_summaries', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('customer_intelligence', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_customers_phone_number'), table_name='customers')
    op.create_index(op.f('ix_customers_phone_number'), 'customers', ['phone_number'], unique=False)
    op.create_unique_constraint('uix_restaurant_phone', 'customers', ['restaurant_id', 'phone_number'])
    op.alter_column('recommendations', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reward_summaries', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reward_summaries', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('recommendations', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('uix_restaurant_phone', 'customers', type_='unique')
    op.drop_index(op.f('ix_customers_phone_number'), table_name='customers')
    op.create_index(op.f('ix_customers_phone_number'), 'customers', ['phone_number'], unique=True)
    op.alter_column('customer_intelligence', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('campaign_summaries', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('business_summaries', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('automation_summaries', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
