"""add_status_to_visits

Revision ID: a34027a626dc
Revises: 518cfd941c5c
Create Date: 2026-06-18 16:40:08.451892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a34027a626dc'
down_revision: Union[str, Sequence[str], None] = '518cfd941c5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_restaurant_user', 'restaurant_users', ['restaurant_id', 'user_id'])
    op.add_column('visits', sa.Column('status', sa.String(), server_default='active', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visits', 'status')
    op.drop_constraint('uix_restaurant_user', 'restaurant_users', type_='unique')
    # ### end Alembic commands ###
