"""Baseline migration

Revision ID: be5662ba1f14
Revises: 
Create Date: 2026-05-21 11:05:35.736671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be5662ba1f14'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('idx_auto_sum_month'), table_name='automation_summaries')
    op.drop_index(op.f('idx_auto_sum_type'), table_name='automation_summaries')
    op.create_index(op.f('ix_automation_summaries_automation_type'), 'automation_summaries', ['automation_type'], unique=False)
    op.create_index(op.f('ix_automation_summaries_period_month'), 'automation_summaries', ['period_month'], unique=False)
    op.drop_index(op.f('idx_bus_sum_type'), table_name='business_summaries')
    op.create_index(op.f('ix_business_summaries_period_type'), 'business_summaries', ['period_type'], unique=False)
    op.create_foreign_key(None, 'messages', 'campaigns', ['campaign_id'], ['id'])
    op.drop_index(op.f('idx_rec_dismissed'), table_name='recommendations')
    op.drop_index(op.f('idx_rec_priority'), table_name='recommendations')
    op.create_index(op.f('ix_recommendations_is_dismissed'), 'recommendations', ['is_dismissed'], unique=False)
    op.create_index(op.f('ix_recommendations_priority'), 'recommendations', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_priority'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_is_dismissed'), table_name='recommendations')
    op.create_index(op.f('idx_rec_priority'), 'recommendations', ['priority'], unique=False)
    op.create_index(op.f('idx_rec_dismissed'), 'recommendations', ['is_dismissed'], unique=False)
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_business_summaries_period_type'), table_name='business_summaries')
    op.create_index(op.f('idx_bus_sum_type'), 'business_summaries', ['period_type'], unique=False)
    op.drop_index(op.f('ix_automation_summaries_period_month'), table_name='automation_summaries')
    op.drop_index(op.f('ix_automation_summaries_automation_type'), table_name='automation_summaries')
    op.create_index(op.f('idx_auto_sum_type'), 'automation_summaries', ['automation_type'], unique=False)
    op.create_index(op.f('idx_auto_sum_month'), 'automation_summaries', ['period_month'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('value_bool', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('value_str', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('settings_pkey'))
    )
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    # ### end Alembic commands ###
