"""remove_unique_constraints

Revision ID: c893ab3fbe50
Revises: d70eafd67b48
Create Date: 2026-05-23 13:57:52.127060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c893ab3fbe50'
down_revision: Union[str, Sequence[str], None] = 'd70eafd67b48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('automation_configs_automation_type_key'), 'automation_configs', type_='unique')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.create_unique_constraint(op.f('automation_configs_automation_type_key'), 'automation_configs', ['automation_type'])
    # ### end Alembic commands ###
