"""add_saas_foundations

Revision ID: d70eafd67b48
Revises: be5662ba1f14
Create Date: 2026-05-23 13:45:40.524030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd70eafd67b48'
down_revision: Union[str, Sequence[str], None] = 'be5662ba1f14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('owner_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('restaurant_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurants_id'), 'restaurants', ['id'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value_bool', sa.Boolean(), nullable=True),
    sa.Column('value_str', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.create_index(op.f('ix_settings_restaurant_id'), 'settings', ['restaurant_id'], unique=False)
    op.create_table('restaurant_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_users_id'), 'restaurant_users', ['id'], unique=False)
    op.add_column('automation_configs', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_automation_configs_restaurant_id'), 'automation_configs', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'automation_configs', 'restaurants', ['restaurant_id'], ['id'])
    op.add_column('automation_history', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_automation_history_restaurant_id'), 'automation_history', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'automation_history', 'restaurants', ['restaurant_id'], ['id'])
    op.add_column('automation_summaries', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_automation_summaries_restaurant_id'), 'automation_summaries', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'automation_summaries', 'restaurants', ['restaurant_id'], ['id'])
    op.add_column('business_summaries', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_business_summaries_restaurant_id'), 'business_summaries', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'business_summaries', 'restaurants', ['restaurant_id'], ['id'])
    op.add_column('campaign_summaries', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_campaign_summaries_restaurant_id'), 'campaign_summaries', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'campaign_summaries', 'restaurants', ['restaurant_id'], ['id'])
    op.add_column('campaigns', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_campaigns_restaurant_id'), 'campaigns', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'campaigns', 'restaurants', ['restaurant_id'], ['id'])
    op.add_column('customer_intelligence', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_customer_intelligence_restaurant_id'), 'customer_intelligence', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'customer_intelligence', 'restaurants', ['restaurant_id'], ['id'])
    op.add_column('customer_profiles', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_customer_profiles_restaurant_id'), 'customer_profiles', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'customer_profiles', 'restaurants', ['restaurant_id'], ['id'])
    op.add_column('customers', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_customers_restaurant_id'), 'customers', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'customers', 'restaurants', ['restaurant_id'], ['id'])
    op.add_column('gov_audit_logs', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_gov_audit_logs_restaurant_id'), 'gov_audit_logs', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'gov_audit_logs', 'restaurants', ['restaurant_id'], ['id'])
    op.add_column('gov_operational_logs', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_gov_operational_logs_restaurant_id'), 'gov_operational_logs', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'gov_operational_logs', 'restaurants', ['restaurant_id'], ['id'])
    op.add_column('loyalty_rewards', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_loyalty_rewards_restaurant_id'), 'loyalty_rewards', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'loyalty_rewards', 'restaurants', ['restaurant_id'], ['id'])
    op.add_column('messages', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_messages_restaurant_id'), 'messages', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'restaurants', ['restaurant_id'], ['id'])
    op.add_column('recommendations', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_recommendations_restaurant_id'), 'recommendations', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'recommendations', 'restaurants', ['restaurant_id'], ['id'])
    op.add_column('reward_redemptions', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_reward_redemptions_restaurant_id'), 'reward_redemptions', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'reward_redemptions', 'restaurants', ['restaurant_id'], ['id'])
    op.add_column('reward_summaries', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_reward_summaries_restaurant_id'), 'reward_summaries', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'reward_summaries', 'restaurants', ['restaurant_id'], ['id'])
    op.add_column('sub_subscriptions', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.drop_constraint('sub_subscriptions_user_id_key', 'sub_subscriptions', type_='unique')
    op.create_unique_constraint(None, 'sub_subscriptions', ['restaurant_id'])
    op.drop_constraint('sub_subscriptions_user_id_fkey', 'sub_subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'sub_subscriptions', 'restaurants', ['restaurant_id'], ['id'])
    
    # === CUSTOM BACKFILL LOGIC ===
    # Insert default restaurant
    op.execute(
        "INSERT INTO restaurants (name, timezone, created_at, updated_at) "
        "VALUES ('Default Restaurant', 'UTC', now(), now()) "
        "ON CONFLICT DO NOTHING"
    )
    
    # Backfill restaurant_id across all tables
    tables = [
        "sub_subscriptions", "automation_configs", "automation_history", 
        "automation_summaries", "business_summaries", "campaign_summaries", 
        "campaigns", "customer_intelligence", "customer_profiles", "customers", 
        "gov_audit_logs", "gov_operational_logs", "loyalty_rewards", "messages", 
        "recommendations", "reward_redemptions", "reward_summaries"
    ]
    for table in tables:
        op.execute(f"UPDATE {table} SET restaurant_id = (SELECT id FROM restaurants ORDER BY id LIMIT 1) WHERE restaurant_id IS NULL")

    # Link all existing OWNER users to the default restaurant
    op.execute(
        "INSERT INTO restaurant_users (restaurant_id, user_id, role, created_at) "
        "SELECT (SELECT id FROM restaurants ORDER BY id LIMIT 1), id, 'OWNER', now() "
        "FROM users WHERE role = 'OWNER' "
        "ON CONFLICT DO NOTHING"
    )
    
    # Make sub_subscriptions.restaurant_id non-nullable
    op.alter_column('sub_subscriptions', 'restaurant_id', nullable=False)
    op.drop_column('sub_subscriptions', 'user_id')
    op.add_column('visits', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.execute("UPDATE visits SET restaurant_id = (SELECT id FROM restaurants ORDER BY id LIMIT 1) WHERE restaurant_id IS NULL")
    op.create_index(op.f('ix_visits_restaurant_id'), 'visits', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'visits', 'restaurants', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visits', type_='foreignkey')
    op.drop_index(op.f('ix_visits_restaurant_id'), table_name='visits')
    op.drop_column('visits', 'restaurant_id')
    op.add_column('sub_subscriptions', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sub_subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('sub_subscriptions_user_id_fkey'), 'sub_subscriptions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'sub_subscriptions', type_='unique')
    op.create_unique_constraint(op.f('sub_subscriptions_user_id_key'), 'sub_subscriptions', ['user_id'])
    op.drop_column('sub_subscriptions', 'restaurant_id')
    op.drop_constraint(None, 'reward_summaries', type_='foreignkey')
    op.drop_index(op.f('ix_reward_summaries_restaurant_id'), table_name='reward_summaries')
    op.drop_column('reward_summaries', 'restaurant_id')
    op.drop_constraint(None, 'reward_redemptions', type_='foreignkey')
    op.drop_index(op.f('ix_reward_redemptions_restaurant_id'), table_name='reward_redemptions')
    op.drop_column('reward_redemptions', 'restaurant_id')
    op.drop_constraint(None, 'recommendations', type_='foreignkey')
    op.drop_index(op.f('ix_recommendations_restaurant_id'), table_name='recommendations')
    op.drop_column('recommendations', 'restaurant_id')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_restaurant_id'), table_name='messages')
    op.drop_column('messages', 'restaurant_id')
    op.drop_constraint(None, 'loyalty_rewards', type_='foreignkey')
    op.drop_index(op.f('ix_loyalty_rewards_restaurant_id'), table_name='loyalty_rewards')
    op.drop_column('loyalty_rewards', 'restaurant_id')
    op.drop_constraint(None, 'gov_operational_logs', type_='foreignkey')
    op.drop_index(op.f('ix_gov_operational_logs_restaurant_id'), table_name='gov_operational_logs')
    op.drop_column('gov_operational_logs', 'restaurant_id')
    op.drop_constraint(None, 'gov_audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_gov_audit_logs_restaurant_id'), table_name='gov_audit_logs')
    op.drop_column('gov_audit_logs', 'restaurant_id')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_index(op.f('ix_customers_restaurant_id'), table_name='customers')
    op.drop_column('customers', 'restaurant_id')
    op.drop_constraint(None, 'customer_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_customer_profiles_restaurant_id'), table_name='customer_profiles')
    op.drop_column('customer_profiles', 'restaurant_id')
    op.drop_constraint(None, 'customer_intelligence', type_='foreignkey')
    op.drop_index(op.f('ix_customer_intelligence_restaurant_id'), table_name='customer_intelligence')
    op.drop_column('customer_intelligence', 'restaurant_id')
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_index(op.f('ix_campaigns_restaurant_id'), table_name='campaigns')
    op.drop_column('campaigns', 'restaurant_id')
    op.drop_constraint(None, 'campaign_summaries', type_='foreignkey')
    op.drop_index(op.f('ix_campaign_summaries_restaurant_id'), table_name='campaign_summaries')
    op.drop_column('campaign_summaries', 'restaurant_id')
    op.drop_constraint(None, 'business_summaries', type_='foreignkey')
    op.drop_index(op.f('ix_business_summaries_restaurant_id'), table_name='business_summaries')
    op.drop_column('business_summaries', 'restaurant_id')
    op.drop_constraint(None, 'automation_summaries', type_='foreignkey')
    op.drop_index(op.f('ix_automation_summaries_restaurant_id'), table_name='automation_summaries')
    op.drop_column('automation_summaries', 'restaurant_id')
    op.drop_constraint(None, 'automation_history', type_='foreignkey')
    op.drop_index(op.f('ix_automation_history_restaurant_id'), table_name='automation_history')
    op.drop_column('automation_history', 'restaurant_id')
    op.drop_constraint(None, 'automation_configs', type_='foreignkey')
    op.drop_index(op.f('ix_automation_configs_restaurant_id'), table_name='automation_configs')
    op.drop_column('automation_configs', 'restaurant_id')
    op.drop_index(op.f('ix_restaurant_users_id'), table_name='restaurant_users')
    op.drop_table('restaurant_users')
    op.drop_index(op.f('ix_settings_restaurant_id'), table_name='settings')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_restaurants_id'), table_name='restaurants')
    op.drop_table('restaurants')
    # ### end Alembic commands ###
